name: CI

on: [push]

jobs:
 sast_scan:
   # Bandit is SAST tool for python to run static application security tests
   # We can use multiple tools for the same job to compare the result
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
       python-version: 3.8

   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
     run: bandit -ll -ii -r . -f json -o bandit-report.json

   - name: Upload Artifact
     uses: actions/upload-artifact@v3
     if: always() # to upload the report file even if Bandit scan step fail
     with:
      name: bandit-findings
      path: bandit-report.json
